name: Upload Package to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install build twine

      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          RELEASE_VERSION=$(echo $GITHUB_REF_NAME | sed 's/v//')
          echo "Publishing version ${RELEASE_VERSION}"
          sed -i "s/\"dev\"/\"${RELEASE_VERSION}\"/" ./src/inka/__init__.py
          python3 -m build
          twine upload dist/*
